# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman
# remote_theme: heliumjk/heliumjk
remote_theme: andrewbanchich/Forty-Jekyll-Theme
author: dxi
description: > 
  data groves for students and instructors

twitter_username: datenXinfos
github_username: dxiai

