# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman
# remote_theme: heliumjk/heliumjk
remote_theme: macrod68/jekyll-materialize-starter-template
author: dxi
description: > 
  data groves for students and instructors

twitter_username: datenXinfos
github_username: dxiai

