remote_theme: janczizikow/sleek
title: daten und infomation
author: dxiai
description: > 
  Resourcen, Tools und News f체r die t채gliche Datenarbeit

tagline: >
  Resourcen, Tools und News f체r die t채gliche Datenarbeit

twitter_username: datenXinfos
github_username: dxiai

navigation:
  - name: Blog
    link: /
  - name: Materialien
    link: /docs/
  - name: Projekte
    link: /projekte
