remote_theme: dxiai/dxiai-theme

title: dxi.ai
author: dxiai
description: > 
  Resourcen, Tools und News f체r die t채gliche Datenarbeit

tagline: >
  Resourcen, Tools und News f체r die t채gliche Datenarbeit

twitter_username: datenXinfos
github_username: dxiai
  
